// Mocks generated by Mockito 5.4.4 from annotations
// in razorerp_weather_app/test/presentation/pages/weather_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hydrated_bloc/hydrated_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:razorerp_weather_app/core/utils/location_service.dart' as _i3;
import 'package:razorerp_weather_app/domain/usecases/get_weather_forecast.dart'
    as _i2;
import 'package:razorerp_weather_app/presentation/bloc/weather_bloc.dart'
    as _i5;
import 'package:razorerp_weather_app/presentation/bloc/weather_event.dart'
    as _i8;
import 'package:razorerp_weather_app/presentation/bloc/weather_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetWeatherForecast_0 extends _i1.SmartFake
    implements _i2.GetWeatherForecast {
  _FakeGetWeatherForecast_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationService_1 extends _i1.SmartFake
    implements _i3.LocationService {
  _FakeLocationService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherState_2 extends _i1.SmartFake implements _i4.WeatherState {
  _FakeWeatherState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherBloc extends _i1.Mock implements _i5.WeatherBloc {
  MockWeatherBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWeatherForecast get getWeatherForecast => (super.noSuchMethod(
        Invocation.getter(#getWeatherForecast),
        returnValue: _FakeGetWeatherForecast_0(
          this,
          Invocation.getter(#getWeatherForecast),
        ),
      ) as _i2.GetWeatherForecast);

  @override
  _i3.LocationService get locationService => (super.noSuchMethod(
        Invocation.getter(#locationService),
        returnValue: _FakeLocationService_1(
          this,
          Invocation.getter(#locationService),
        ),
      ) as _i3.LocationService);

  @override
  _i4.WeatherState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWeatherState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.WeatherState);

  @override
  _i6.Stream<_i4.WeatherState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i4.WeatherState>.empty(),
      ) as _i6.Stream<_i4.WeatherState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get storagePrefix => (super.noSuchMethod(
        Invocation.getter(#storagePrefix),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storagePrefix),
        ),
      ) as String);

  @override
  String get storageToken => (super.noSuchMethod(
        Invocation.getter(#storageToken),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#storageToken),
        ),
      ) as String);

  @override
  Map<String, dynamic>? toJson(_i4.WeatherState? state) =>
      (super.noSuchMethod(Invocation.method(
        #toJson,
        [state],
      )) as Map<String, dynamic>?);

  @override
  void add(_i8.WeatherEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i8.WeatherEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.WeatherState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i8.WeatherEvent>(
    _i9.EventHandler<E, _i4.WeatherState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i9.Transition<_i8.WeatherEvent, _i4.WeatherState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void onChange(_i9.Change<_i4.WeatherState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hydrate() => super.noSuchMethod(
        Invocation.method(
          #hydrate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
